using AleaSim.Domain.Entities;
using AleaSim.Domain.Interfaces;

namespace AleaSim.Domain.Services;

public class VaultService : IVaultService {
    private readonly object _lock = new();

    public bool ProcessBet(Guid userId, decimal amount, IGameRepository repo) {
        // Note: Transaction management is handled by the caller (GameEngine)
        var user = repo.GetUser(userId);
        if (user == null) return false;

        // 1. Check Bonus Balance First
        if (user.BonusBalance > 0) {
            if (user.BonusBalance >= amount) {
                user.BonusBalance -= amount;
                
                // Update Wagering Progress
                if (user.WageringRequirement > 0) {
                    user.WageringProgress += amount;
                    CheckWageringCompletion(user);
                }
                
                repo.UpdateUser(user);
                return true;
            }
            else {
                // Not enough bonus funds for this bet.
                // Policy: User must use Real Balance if Bonus is insufficient for full bet?
                // OR split bet? For MVP, let's assume Mixed Pay is allowed.
                decimal remainder = amount - user.BonusBalance;
                user.BonusBalance = 0; // All bonus used
                
                // Track wagering for the bonus part
                if (user.WageringRequirement > 0) {
                     user.WageringProgress += (amount - remainder);
                     CheckWageringCompletion(user);
                }

                if (user.Balance >= remainder) {
                    user.Balance -= remainder;
                    repo.UpdateUser(user);
                    return true;
                }
                return false; // Insufficient total funds
            }
        }

        // 2. Real Balance
        if (user.Balance >= amount) {
            user.Balance -= amount;
            repo.UpdateUser(user);
            return true;
        }

        return false;
    }

    public void ProcessWin(Guid userId, decimal amount, IGameRepository repo) {
        var user = repo.GetUser(userId);
        if (user == null) return;

        // Logic: If user played with Bonus, win goes to Bonus?
        // Simplification: If User has ACTIVE Bonus Requirement, ALL wins go to Bonus Balance (Locked).
        // This prevents users from cashing out wins generated by bonus money before wagering is done.
        
        if (user.WageringRequirement > user.WageringProgress) {
            user.BonusBalance += amount;
        } else {
            user.Balance += amount;
        }
        
        repo.UpdateUser(user);
    }

    public bool CanAffordWin(Guid userId, Guid gameId, decimal winAmount, IGameRepository repo) {
        lock (_lock) {
            var game = repo.GetGame(gameId);
            if (game == null) return false;

            // 1. Check Global/Game Pool
            if (game.PoolBalance < winAmount) return false;

            // 2. Check Personal RTP (Shadow Wallet) - Optional strictly enforcement?
            // For now, let's trust the Pool check mostly, but maybe check if pRTP isn't insane?
            // We skip pRTP check here because Brain already checked it before asking.
            // Vault mainly cares about SOLVENCY (Do we have the cash?).

            return true;
        }
    }

    public void CreditBonus(Guid userId, decimal amount, decimal wageringRequirement, IGameRepository repo) {
        var user = repo.GetUser(userId);
        if (user == null) return;

        user.BonusBalance += amount;
        user.WageringRequirement += wageringRequirement; // Add to existing requirement
        user.BonusLastUpdated = DateTime.UtcNow;
        repo.UpdateUser(user);
    }

    public bool CashoutBonus(Guid userId, IGameRepository repo) {
        var user = repo.GetUser(userId);
        if (user == null || user.BonusBalance <= 0) return false;

        decimal amountToCredit = 0;

        if (user.BonusBalance >= 100) {
            // The 1/10 Rule
            amountToCredit = user.BonusBalance * 0.10m;
        } 
        // If < 100, amountToCredit remains 0 (Forfeit)

        user.Balance += amountToCredit;
        user.BonusBalance = 0;
        user.WageringRequirement = 0;
        user.WageringProgress = 0;

        repo.UpdateUser(user);
        return true;
    }

    private void CheckWageringCompletion(User user) {
        if (user.WageringProgress >= user.WageringRequirement) {
            // Unlocked! Move Bonus to Real.
            user.Balance += user.BonusBalance;
            user.BonusBalance = 0;
            user.WageringRequirement = 0;
            user.WageringProgress = 0;
        }
    }
}
