// <auto-generated />
using System;
using AleaSim.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AleaSim.Persistence.Migrations
{
    [DbContext(typeof(AleaSimDbContext))]
    [Migration("20260312192441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AleaSim.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ConditionValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RewardAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e54c597b-1189-444c-8ee6-5187fad2e8d7"),
                            Category = "General",
                            ConditionType = "TotalBets",
                            ConditionValue = 1m,
                            Description = "Place your first bet",
                            Icon = "🎯",
                            Name = "First Blood",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("22aa7380-e596-43bf-9e58-e1db17cc52bb"),
                            Category = "General",
                            ConditionType = "TotalWagered",
                            ConditionValue = 5000m,
                            Description = "Wager more than $5,000 total",
                            Icon = "💎",
                            Name = "High Roller",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("f1de42a9-d3c1-4def-a93e-576e3a961b3d"),
                            Category = "General",
                            ConditionType = "TotalWagered",
                            ConditionValue = 50000m,
                            Description = "Wager more than $50,000 total",
                            Icon = "🐋",
                            Name = "The Whale",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("593880d2-d2f0-485f-84e3-198f6dbed3b5"),
                            Category = "General",
                            ConditionType = "MaxMultiplier",
                            ConditionValue = 100m,
                            Description = "Hit a win over 100x multiplier",
                            Icon = "⭐",
                            Name = "Lucky Star",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("37b67d61-c310-45eb-b133-7e43e1c847d5"),
                            Category = "General",
                            ConditionType = "LevelReached",
                            ConditionValue = 10m,
                            Description = "Reach Level 10",
                            Icon = "🎖️",
                            Name = "Veteran",
                            RewardAmount = 0m
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GameRoundId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoundId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderAvatarUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PoolBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TargetRTP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            MaxBet = 1000m,
                            MinBet = 0.1m,
                            Name = "Clover Chase",
                            PoolBalance = 0m,
                            Provider = "AleaSim Originals",
                            TargetRTP = 0.965m,
                            Type = "slot"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            MaxBet = 1000m,
                            MinBet = 0.1m,
                            Name = "Roulette Royale",
                            PoolBalance = 0m,
                            Provider = "AleaSim Originals",
                            TargetRTP = 0.973m,
                            Type = "roulette"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            MaxBet = 1000m,
                            MinBet = 0.1m,
                            Name = "Blackjack High",
                            PoolBalance = 0m,
                            Provider = "AleaSim Originals",
                            TargetRTP = 0.992m,
                            Type = "blackjack"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            MaxBet = 1000m,
                            MinBet = 0.1m,
                            Name = "Neon Dice",
                            PoolBalance = 0m,
                            Provider = "AleaSim Originals",
                            TargetRTP = 0.990m,
                            Type = "dice"
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DirectiveId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nonce")
                        .HasColumnType("int");

                    b.Property<string>("RandomResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerSeedHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShadowBrainResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TargetWinAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalBetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerSeedHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GlobalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Key");

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            Key = "GlobalTargetRtp",
                            Description = "Target RTP percentage for the system",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6703),
                            Value = "95.0"
                        },
                        new
                        {
                            Key = "EmergencyStop",
                            Description = "Master switch to pause all games",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6705),
                            Value = "false"
                        },
                        new
                        {
                            Key = "VolatilityMode",
                            Description = "Global volatility profile (Low, Standard, High)",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6707),
                            Value = "Standard"
                        },
                        new
                        {
                            Key = "Content_Help",
                            Description = "Help Page Introduction Content",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6708),
                            Value = "Welcome to AleaSim Help Center. Use the expansion panels below to find answers."
                        },
                        new
                        {
                            Key = "Content_Terms",
                            Description = "Terms of Service Content",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6709),
                            Value = "By using AleaSim, you agree to our terms of service..."
                        },
                        new
                        {
                            Key = "Content_Privacy",
                            Description = "Privacy Policy Content",
                            LastUpdated = new DateTime(2026, 3, 12, 19, 24, 41, 177, DateTimeKind.Utc).AddTicks(6711),
                            Value = "We value your privacy. Your data is encrypted..."
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Jackpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ContributionRate")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("MustDropAt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jackpots");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameRoundId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsJackpotWin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("WinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoundId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("ActualRtp")
                        .HasColumnType("double");

                    b.Property<double>("AvgSpinInterval")
                        .HasColumnType("double");

                    b.Property<int>("CashbackLevel")
                        .HasColumnType("int");

                    b.Property<double>("ChurnRiskScore")
                        .HasColumnType("double");

                    b.Property<decimal>("CurrentSessionRtp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastSpinTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LossStreak")
                        .HasColumnType("int");

                    b.Property<int>("LuckyCloverLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PendingCashback")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ShadowBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SymbolAffinityJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWagered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VolatilityScore")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("XpBoostLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("RewardAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ce1bf67-8bf1-4898-808b-5dd1428ad465"),
                            Description = "Complete 50 spins on any slot",
                            GoalType = "SpinCount",
                            IsActive = true,
                            RewardAmount = 10m,
                            TargetValue = 50m,
                            Title = "Daily Spinner"
                        },
                        new
                        {
                            Id = new Guid("a56f526b-d91b-41dc-a483-d68ed8887029"),
                            Description = "Wager a total of $1,000",
                            GoalType = "TotalWager",
                            IsActive = true,
                            RewardAmount = 50m,
                            TargetValue = 1000m,
                            Title = "High Stakes"
                        },
                        new
                        {
                            Id = new Guid("23e39603-f644-4de3-b3bc-7a109c40862c"),
                            Description = "Win a total of $500",
                            GoalType = "WinAmount",
                            IsActive = true,
                            RewardAmount = 25m,
                            TargetValue = 500m,
                            Title = "Big Win Hunter"
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.RTPStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TotalRounds")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalWagered")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("RTPStatistics");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.SupportMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("RoundCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayout")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TournamentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TournamentWinners");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ResultingBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BonusBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("BonusLastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<decimal?>("DailyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastBetTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastDailySpin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastStreakClaim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("MonthlyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("WageringProgress")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("WageringRequirement")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WeeklyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentXP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LifetimeXP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserProgressions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserQuestProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("UserQuestProgressions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal>("WageringRequirement")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AleaSim.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserQuestProgress", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Profile");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
