// <auto-generated />
using System;
using AleaSim.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AleaSim.Persistence.Migrations
{
    [DbContext(typeof(AleaSimDbContext))]
    [Migration("20260220024654_AddUserSettingsAndSecurity")]
    partial class AddUserSettingsAndSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AleaSim.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ConditionValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RewardAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e0a2d2f-d39f-48c9-ac67-ee44711e81a6"),
                            Category = "General",
                            ConditionType = "TotalBets",
                            ConditionValue = 1m,
                            Description = "Place your first bet",
                            Icon = "🎯",
                            Name = "First Blood",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("fc4a6a4d-986a-4da7-94b5-404fc46ccc68"),
                            Category = "General",
                            ConditionType = "TotalWagered",
                            ConditionValue = 5000m,
                            Description = "Wager more than $5,000 total",
                            Icon = "💎",
                            Name = "High Roller",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("49aa2988-3b48-40b7-abdb-1bbc8d838c4d"),
                            Category = "General",
                            ConditionType = "TotalWagered",
                            ConditionValue = 50000m,
                            Description = "Wager more than $50,000 total",
                            Icon = "🐋",
                            Name = "The Whale",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("90df2b26-8c02-4e2a-8f64-6128d5159f21"),
                            Category = "General",
                            ConditionType = "MaxMultiplier",
                            ConditionValue = 100m,
                            Description = "Hit a win over 100x multiplier",
                            Icon = "⭐",
                            Name = "Lucky Star",
                            RewardAmount = 0m
                        },
                        new
                        {
                            Id = new Guid("0ef77176-d741-4379-8146-80daefef7309"),
                            Category = "General",
                            ConditionType = "LevelReached",
                            ConditionValue = 10m,
                            Description = "Reach Level 10",
                            Icon = "🎖️",
                            Name = "Veteran",
                            RewardAmount = 0m
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GameRoundId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoundId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinBet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PoolBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TargetRTP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DirectiveId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nonce")
                        .HasColumnType("int");

                    b.Property<string>("RandomResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerSeedHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShadowBrainResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TargetWinAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalBetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerSeedHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GlobalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Key");

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            Key = "GlobalTargetRtp",
                            Description = "Target RTP percentage for the system",
                            LastUpdated = new DateTime(2026, 2, 20, 2, 46, 53, 716, DateTimeKind.Utc).AddTicks(3046),
                            Value = "95.0"
                        },
                        new
                        {
                            Key = "EmergencyStop",
                            Description = "Master switch to pause all games",
                            LastUpdated = new DateTime(2026, 2, 20, 2, 46, 53, 716, DateTimeKind.Utc).AddTicks(3049),
                            Value = "false"
                        },
                        new
                        {
                            Key = "VolatilityMode",
                            Description = "Global volatility profile (Low, Standard, High)",
                            LastUpdated = new DateTime(2026, 2, 20, 2, 46, 53, 716, DateTimeKind.Utc).AddTicks(3051),
                            Value = "Standard"
                        });
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Jackpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ContributionRate")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("MustDropAt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jackpots");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameRoundId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsJackpotWin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("WinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoundId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("ActualRtp")
                        .HasColumnType("double");

                    b.Property<double>("AvgSpinInterval")
                        .HasColumnType("double");

                    b.Property<int>("CashbackLevel")
                        .HasColumnType("int");

                    b.Property<double>("ChurnRiskScore")
                        .HasColumnType("double");

                    b.Property<decimal>("CurrentSessionRtp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastSpinTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LossStreak")
                        .HasColumnType("int");

                    b.Property<int>("LuckyCloverLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShadowBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SymbolAffinityJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWagered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VolatilityScore")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("XpBoostLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RewardAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.RTPStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastCalculated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TotalRounds")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalWagered")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("RTPStatistics");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("RoundCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayout")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalWagered")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TournamentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TournamentWinners");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ResultingBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BonusBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("BonusLastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<decimal?>("DailyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastBetTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastDailySpin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastStreakClaim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("MonthlyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("WageringProgress")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("WageringRequirement")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WeeklyLossLimit")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentXP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LifetimeXP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserProgressions");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal>("WageringRequirement")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AleaSim.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("AleaSim.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AleaSim.Domain.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Profile");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
